pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: |
      sudo apt-get install dpkg fakeroot -y
    displayName: "Install dpkg & fakeroot"

  - script: |
      yarn install
    displayName: "Yarn install"

  - script: |
      COMMITS="$(git log $(git describe --tags --abbrev=0)..HEAD --oneline | grep -iv merge)"
      echo $COMMITS
      if [[ $COMMITS ]]; then
          echo "Commits found since last tag; only running make to ensure build consistency."
          yarn run make
      else
          echo "No commits found since last tag; making and publishing to GitHub."
          GITHUB_TOKEN=$(GITHUB_TOKEN) yarn run publish
      fi
    displayName: "Make or Publish"
